### ISSUE TITLE
Tap menu Error

### ISSUE THREAD

**Issue by karpotkin** [khanghoang/RNSideMenu#1]
https://www.dropbox.com/s/pishfsf4f1rmkc9/Screenshot%202015-04-03%2012.58.03.png?dl=0

**Comment by khanghoang** [comment]
@karpotkin there is error because React Native updates and they change to use millisecond instead of millisecond https://github.com/khanghoang/RNSideMenu/commit/03363acbb7d29bb9e47c7bba96c45b6e55ce40a9

**Comment by karpotkin** [comment]
thanks!
